name: deployCC

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  builds:

    name: deployCC
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rlgoDzvc -i --delete"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: "my_bots/capital_cities"
        EXCLUDE: ".git*/,.github*/,.gitignore"
        SCRIPT_BEFORE: |
          whoami
          ls -al
          docker ps -q --filter "name=CC" | xargs -r docker stop
        SCRIPT_AFTER: |
          whoami
          ls -al
          cd my_bots/capital_cities
          echo API_TOKEN=${{ SECRETS.API_TOKEN }} > .env
          docker build -t bot .
          docker rmi $(docker images -f "dangling=true" -q)
          docker run -q --rm --name CC bot
        
      
